name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Zine
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: zine --git --rev 443f6de824f1ec38d05e291186e9b87176345c35
    - name: Build
      run: zine build
    - name: Publish Github Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
